# ASP.NET Core (.NET Framework)


# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest' 

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: BuildAndTest
    displayName: 'Build and Test'
    jobs:

      - job: ArtifactRegistration
        steps:

          - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
            displayName: 'ServiceNow DevOps Agent Artifact Registration'
            inputs:
              connectedServiceName: 'demotechnologywf14058-Corpsite Mobile-ServiceNow DevOps Service Connection'
              artifactsPayload: |
                {
                  "artifacts": [
                      {
                        "name": "BuildDrop",
                        "version": "1.$(Build.BuildId)",
                        "semanticVersion": "1.$(Build.BuildId).0",
                        "BuildNumber": "$(Build.BuildNumber)",
                        "repositoryName": "DeployableRepo"
                      }
                  ]
                }

  - stage: QAT
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    displayName: 'QAT'
    jobs:
      - job: Test
        steps:
          - task: ServiceNow-DevOps-Build-Sonar-Registration@1
            inputs:
              connectedServiceName: 'demotechnologywf14058-Corpsite Mobile-ServiceNow DevOps Service Connection'
              sonarProjectKey: 'prathyushkondapalli_DevOpsDemoHub'
              sonarInstanceUrl: 'https://sonarcloud.io/'
              
          - task: VSTest@2
            inputs:
              platform: '$(buildPlatform)'
              configuration: '$(buildConfiguration)'

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'VSTest'
              testResultsFiles: |
                **/TEST-*.xml
                d:\a\_temp\TestResults\*.trx
              mergeTestResults: true
      - job: PackageRegistration
        dependsOn: Test
        steps:
        - task: ServiceNow-DevOps-Agent-Package-Registration@1
          displayName: 'ServiceNow DevOps Agent Package Registration'
          inputs:
            connectedServiceName: 'demotechnologywf14058-Corpsite Mobile-ServiceNow DevOps Service Connection'
            packageName: 'see-power-amp-$(build.buildId)'
            artifactsPayload: |
                {
                "name": "see-power-amp-connectors-breeze",
                "artifacts": [
                {
                "name": "BuildDrop",
                "repositoryName": "DeployableRepo",
                "version": "1.$(Build.BuildId)",

                "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                "taskExecutionNumber":"$(build.buildId)",
                "stageName":"$(system.jobDisplayName)",
                "attemptNumber":"$(system.jobAttempt)",
                "branchName":"$(build.sourceBranchName)"
                }],
                "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                "taskExecutionNumber":"$(Build.BuildId)",
                "stageName":"$(system.jobDisplayName)",
                "attemptNumber":"$(system.jobAttempt)",
                "branchName":"$(build.sourceBranchName)"
                }
          enabled: true

  - stage: ChangeAcceleration
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    dependsOn: QAT
    displayName: 'ChangeAcceleration'
    jobs:
      - job: ChangeAcceleration
        pool: server
        steps:
        - task: ServiceNow-DevOps-Server-Change-Acceleration@1
          inputs:
            connectedServiceName: 'demotechnologywf14058-Corpsite Mobile-ServiceNow DevOps Service Connection'
            changeRequestDetails: |
              {
                "setCloseCode" : true,
                "attributes": {
                  "requested_by":{
                    "name":"DevOps Integration User"
                    },
                  "short_description":"Automated software deployment for Enterprise-DevOps/sede-pt-bam",
                  "description":"Deploying software to Enterprise-DevOps/sede-pt-bam which is integrated with the CI/CD pipeline. This software has gone through integrated testing.",
                  "implementation_plan":"Software update is tested and results can be found in 'Test Summaries' Tab; When the change is approved the implementation happens automated by the CI/CD pipeline within the change planned start and end time window.",
                  "backout_plan":"When software fails in production, the previous software release will be re-deployed.",
                  "test_plan":"Testing if the software was successfully deployed happens either \n1) manually by the developer or \n2) automated via the CI/CD pipeline"
                  }
                }
                
  - stage: ProdDeploy
    displayName: 'Production Deployment'
    dependsOn: ChangeAcceleration
    jobs:
      - job: 'Deploy'
        displayName: 'Deployment'
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
                echo 'Deploy completed'
